#!/bin/sh -e

. uniqueness.sh

GT_SRC_DIR=/var/www/servers/genometools.org/htdocs/pub
GT_TAR_NAME=genometools-unstable.tar.gz
GT_DIR=genometools-unstable

GTH_SRC_DIR=$HOME/gth
GTH_TAR_NAME=genomethreader-src-current.tar.gz
GTH_DIR=genomethreader-src-current
GTH_BIN=$HOME/gtmetascripts/gth/genomethreader-src-current/bin

VMATCH_SRC_DIR=$HOME/lscsa
VMATCH_TAR_NAME=vstree-src-current.tar.gz
VMATCH_DIR=vstree-src-current

METASCRIPTS_DIR=$HOME/gtmetascripts

# source git repository used for `git show`
export GIT_DIR=$HOME/gth/genomethreader.git

if ( [ $GT_SRC_DIR/$GT_TAR_NAME -nt $METASCRIPTS_DIR/gth/$GT_TAR_NAME ] ||
     [ $GTH_SRC_DIR/$GTH_TAR_NAME -nt $METASCRIPTS_DIR/gth/$GTH_TAR_NAME ] ||
     [ $VMATCH_SRC_DIR/$VMATCH_TAR_NAME -nt \
       $METASCRIPTS_DIR/gth/$VMATCH_TAR_NAME ] ) \
   && is_unique
then
  COMMIT=`zcat $GTH_SRC_DIR/$GTH_TAR_NAME | git get-tar-commit-id`
  git show --stat $COMMIT

  # build libgenometools first
  cp -f $GT_SRC_DIR/$GT_TAR_NAME $METASCRIPTS_DIR/gth
  rm -rf $METASCRIPTS_DIR/gth/$GT_DIR
  rm -rf $METASCRIPTS_DIR/gth/genometools
  cd $METASCRIPTS_DIR/gth
  tar xzf $GT_TAR_NAME
  mv $GT_DIR genometools
  cd genometools
  make 32bit=yes cairo=no > /dev/null

  # build vstree
  cp -f $VMATCH_SRC_DIR/$VMATCH_TAR_NAME $METASCRIPTS_DIR/gth
  rm -rf $METASCRIPTS_DIR/gth/$VMATCH_DIR
  rm -rf $METASCRIPTS_DIR/gth/vstree
  cd $METASCRIPTS_DIR/gth
  tar xzf $VMATCH_TAR_NAME
  mv $VMATCH_DIR vstree
  cd vstree/src
  mklink.sh linux-gcc
  make licensemanager=no > /dev/null

  # build GenomeThreader
  cp -f $GTH_SRC_DIR/$GTH_TAR_NAME $METASCRIPTS_DIR/gth
  rm -rf $METASCRIPTS_DIR/gth/$GTH_DIR
  cd $METASCRIPTS_DIR/gth
  tar xzf $GTH_TAR_NAME
  cd $GTH_DIR
  # compile
  make licensemanager=no > /dev/null
  # train BSSMs
  make licensemanager=no train > /dev/null
  # test (new stest framework)
  make licensemanager=no memcheck=yes gthtestdata=$HOME/gthtestdata test || true
  # test (old autotest framework)
  cd gthtestsuite
  env PATH=$PATH:$GTH_BIN \
      BSSMDIR=$GTH_BIN/bssm \
      GTHDATADIR=$METASCRIPTS_DIR/gth/$GTH_DIR/gthdata/gth \
      GTHTESTDATADIR=$HOME/gthtestdata \
      VMATCHCOMMENTTOSTDOUT=on \
  time ./testsuite
  cd ..
  # make distribution (testing)
  make licensemanager=no dist > /dev/null
fi
